import pygame

pygame.init()
info = pygame.display.Info()
# Основные настройки игры

# Настройки игрового окна
SCREEN_WIDTH = info.current_w
SCREEN_HEIGHT = info.current_h
SCREEN_SIZE = [SCREEN_WIDTH, SCREEN_HEIGHT]
CENTER_POINT = SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2
FPS = 60

# Настройки кубов
SCALE_COEFFICIENT = 1
STANDARD_CUBE_WIDTH = 104
STANDARD_CUBE_HEIGHT = 134
SCALED_CUBE_WIDTH = STANDARD_CUBE_WIDTH * SCALE_COEFFICIENT
SCALED_CUBE_HEIGHT = STANDARD_CUBE_HEIGHT * SCALE_COEFFICIENT
SCALED_TOP_RECT_HEIGHT = 60
SCALED_TOP_RECT_WIDTH = SCALED_CUBE_WIDTH

# Настройка слоёв
DELTA_LAYER = -1
# Предметы, лежащие на слое выше будут уменьшать свой row, col на -1
SECOND_LAYER = 0 + DELTA_LAYER

# Игрок
HEIGHT_PLAYER = 25
WIDTH_PLAYER = 65
# (значение используется для отрисовки и подсчёта координаты на экране)
# Отступы для корректной отрисовки игрока
MARGIN_TOP_PLAYER = SCALED_TOP_RECT_HEIGHT // 2
MARGIN_LEFT_PLAYER = (SCALED_CUBE_WIDTH - WIDTH_PLAYER)

# pygame gui
BUTTON_SIZE = (200, 60)
BUTTON_SIZE_2 = (150, 35)
MARGIN_LEFT_BUTTON = -BUTTON_SIZE[0] // 2
MARGIN_TOP_BUTTON = -BUTTON_SIZE[1] // 2
UPGRADE_IMAGE_SIZE = [200, 200]

MARGIN_TOP_HEART = 10
MATGIN_RIGHT_HEART = 5

MARGIN_BOTTOM_IMAGE = UPGRADE_IMAGE_SIZE[1]

DATA_PATH = '\\data'
